
CREATE TABLE IF NOT EXISTS clients
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         VARCHAR(255) NOT NULL UNIQUE,
    external_id       VARCHAR(255),
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    middle_name       VARCHAR(255),
    birth_date        DATE,
    tax_id            VARCHAR(255),
    passport_number   VARCHAR(255),
    email             VARCHAR(255),
    phone             VARCHAR(255),
    residency_country VARCHAR(255),
    risk_score        INT,
    kyc_status        VARCHAR(50),
    aml_flag          BOOLEAN,
    active            BOOLEAN,
    blocked           BOOLEAN,
    created_at        DATE         NOT NULL DEFAULT CURRENT_DATE,
    updated_at        DATE
);
